Numpy: Numerical Python demektir.

Numpy kullanım alanları:
1. Sayısal/Matematiksel işlemler
2. Bilimsel hesaplamalar
3. Arrayler/Çok Boyutlu Arrayler/Matrisler üzerinde

Listelere benzerdir. Farkı: verimli veri saklama ve **vektörel operasyonlar**dır

Python'ın listelerinde veri tutarken, liste içerisinde saklanan her bir değer için veri ve ardından tip bilgisi tutuluyor. Her bir değer için bunları yapmak daha ağır programlar ortaya çıkmasına sebep oluyor. 

Numpy'da ise Numpy listeleri içerisinde saklanan elemanlar 1 adet veritipine sahip olabilir, ve belirli büyüklükte olabilir. Numpy bizi buna zorluyor ancak bu da inanılmaz büyük performans artışına sebep oluyor

# Numpy Array'i Oluşturmak

In [3]:
import numpy as np

In [11]:
a = np.array([1,2,3,4,5])
type(a)

numpy.ndarray

In [17]:
# numpy'ın vektörler içerisindeki tüm değerleri aynı yaptığından bahsetmiştik. Görelim:

np.array([1, 2.5, 3, 4.1])
# hem float hem int içeren bir dizinin tüm elemanlarını numpy float'a çevirdi. Sabit tip baskısı

array([1. , 2.5, 3. , 4.1])

In [19]:
np.array([1.2, 3.17, 25.5], dtype="int") 
# eğer spesifik olarak istediğimiz bir tip varsa belirtebiliriz. Hepsi ona döner

array([ 1,  3, 25])

Sıfırdan Array Oluşturmak(değer vermeden)

In [29]:
np.zeros(10, dtype=int) # 10 elemanlı bir array oluşturdu. Zeros olarak oluşturduğumuz için, içine sıfırlar atadı

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [65]:
np.ones((3,5),dtype=int) # ones olarak oluşturduğumuzdan içerisinde 1'lerden oluşan [3][5]'lik bir array oluşturdu

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [81]:
np.full((3,5), 5) # bu şekilde de default olarak içerisine gelecek sayıyı aynı fonksiyonla belirtebiliriz. default dtype = int

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [98]:
np.arange(0, 31, 3) # 0'dan başla, 31'e kadar 3er 3er atlayarak bir array oluştur. uç değer dahil değil

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [100]:
np.linspace(0,1,10) # 0 ile 1 arasını(0 ile 1 de dahil) 10 eşit parçaya böl ve bu parçaları uçlarla birlikte ekle

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [104]:
np.random.normal(10,4,(2,2)) # içerisindeki sayıların ortalaması 10, standart sapması 4 olan 2x2 matris oluştur

array([[ 0.89038774, 10.23123441],
       [13.67866332,  8.97052329]])

In [120]:
np.random.randint(0, 11, (3,4)) # burada mean ya da standart sapma değerleri yok. 
# rastgele 0'den 11'e kadar(11 dahil değil) değerler üretip belirttiğimiz matrise koydu

array([[ 8,  8,  4,  2],
       [ 3, 10,  9,  4],
       [ 4,  1,  1,  0]])

# Numpy array'inin özellikleri

* ndim  : boyut sayısı
* shape : boyut bigisi
* size  : toplam eleman sayısı
* dtype : array veritipi

In [124]:
import numpy as np

In [130]:
np.random.randint(0,10,size=10) # 0'dan 10'a rastgele oluşturulmuş 10 adet eleman olan bir array oluştur

array([5, 1, 4, 9, 4, 2, 4, 4, 9, 4])

In [132]:
a = np.random.randint(0,10,size=10) # özelliklerini görebilmek için bir önceki hücrenin aynısını atadım

In [140]:
a.ndim # 1 boyutlu

1

In [150]:
a.shape # 1 boyutlu olduğundan 1.boyutun bilgisini 10 adet elemanı var diyerek gösterdi

(10,)

In [148]:
a.size # 10 adet eleman var

10

In [154]:
a.dtype # içerisinde int değerler var

dtype('int32')

In [166]:
b = np.random.randint(0, 10, size=(3,5)) # 3 boyutlu ve her boyutu 0'dan 10'a rastgele 5 eleman içeren array
b

array([[2, 4, 3, 9, 4],
       [6, 2, 6, 2, 8],
       [3, 8, 4, 1, 5]])

In [162]:
b.ndim # 2 boyutlu

2

In [168]:
b.shape # 3 boyutlu 5 elemanlı

(3, 5)

In [178]:
b.size # 3*5'den 15 adet eleman var

15

In [180]:
b.dtype # içerisinde int değerler var

dtype('int32')

# Var olan Numpy arrayini yeniden şekillendirme: reshaping

Fonksiyonlarımızın ya da döngülerimizin ürettiği çıktılar tek bir boyutta ya da tek bir arrray formunda gerçekleşebiliyor. Bunları bazen tek boyuttan çok boyuta ya da çok boyuttan tek boyuta indirmemiz gerekiyor. Bu yapısal dönüşümleri de reshape fonksiyonuyla doğru bir şekilde yaparız

In [198]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [226]:
# yukarıdaki array'imizi 3x3'lük matris'e çevirelim.

np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Array Birleştirme(Concatenation)

In [4]:
import numpy as np

In [8]:
x = np.array([1,2,3])
y = np.array([4,5,6])

# şimdi bunları birleştiricez

In [12]:
np.concatenate([x,y]) # burada x ve y arraylerinin birleşimini yaptık

array([1, 2, 3, 4, 5, 6])

In [14]:
# iki boyut

In [138]:
a = np.array([[1,2,3],
              [4,5,6]])

b = np.array([[7,8,9],
              [10,11,12]])

np.concatenate([a,b])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [142]:
# eğer y ekseninde birleştirmek istersem axis değerini güncellerim. Axis eksen belirtmek için vardır. 1=x  0=y

np.concatenate([a,b],axis=1) # x eksenine ekleme yaptı, sütun bazında değil, satır bazında çoğaldı arrayimiz

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

# Array Ayırma(Splitting) 

In [41]:
x = np.array([1,2,3,99,99,3,2,1]) 

# şimdi buradan değerleri sırasıyla 1,2,3 99,99 ve 3,2,1 olan 3 farklı array çıkartıcaz

In [78]:
np.split(x, [3,5]) # x arrayinin 0-3, 3-5, 5-8 eleman arasını 3 farklı arraye böler. 

# Verilen index numaraları dahil değildir. Yani burada 0.indexten 3.index'e kadar(3 dahil değil), 3'ten 5'e kadar 

a,b,c = np.split(x, [3,5]) # burada da sırasıyla arrayleri değerlere atar

In [56]:
a

array([1, 2, 3])

In [58]:
b

array([99, 99])

In [60]:
c

array([3, 2, 1])

In [62]:
# iki boyutlu ayırma

In [76]:
m = np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [144]:
x,y = np.vsplit(m,[2]) # diziyi x eksenine göre böler. burada 2.row'a kadar ve sonrası olarak ayrı ayrı böler. default axis = 1

# 2.satıra kadar olanları, 2.satırdan sonrasını da ayrı ayrı olmak üzere 2 farklı arraye böl 

In [82]:
x

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [84]:
y

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [146]:
x,y = np.hsplit(m,[2]) # diziyi y eksenine göre böler. burada 2.column'a kadar ve sonrası olarak ayrı ayrı böler. default axis = 0

In [98]:
x

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [100]:
y

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

# Array Sıralama(Sorting)

In [120]:
v = np.array([2,1,4,3,5])

In [122]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [126]:
m = np.random.normal(20,5,(3,3)) # ortalaması 20, standart sapması 5 olan 3x3'lük array oluştur

m

array([[16.43056702, 17.18507992, 13.23769613],
       [14.89604104,  8.88933784, 25.67596953],
       [10.73209022, 19.7790356 , 22.50526582]])

In [150]:
np.sort(m, axis=1) # x eksenine göre sıraladı

array([[13.23769613, 16.43056702, 17.18507992],
       [ 8.88933784, 14.89604104, 25.67596953],
       [10.73209022, 19.7790356 , 22.50526582]])

In [148]:
np.sort(m, axis=0) # y eksenine göre sıraladı

array([[10.73209022,  8.88933784, 13.23769613],
       [14.89604104, 17.18507992, 22.50526582],
       [16.43056702, 19.7790356 , 25.67596953]])

# Index ile Elemanlara Erişmek

In [162]:
import numpy as np
a = np.random.randint(10,size=10)
a

array([8, 1, 6, 5, 9, 3, 9, 8, 7, 4])

In [164]:
a[0]

8

In [166]:
a[-2]

7

In [170]:
a[0] = 100
a

array([100,   1,   6,   5,   9,   3,   9,   8,   7,   4])

In [172]:
# iki boyutlu arraylerde

In [178]:
m = np.random.randint(10, size=(3,5))
m

array([[1, 6, 3, 7, 8],
       [6, 6, 4, 8, 5],
       [0, 2, 9, 1, 1]])

In [186]:
m[0][0] # 1.satır, 1.eleman 

1

In [190]:
m[1][2] # 2.satır, 3.eleman

4

In [194]:
m[2][4] # 3.satır, 5.eleman

1

# Array Alt Kümesindeki Elemanlara Erişmek(Slicing)

In [199]:
a = np.arange(20,30) # 20 ile 30 arasındaki sayılardan oluşan bir array oluştur 
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [201]:
# Slicing:
a[0:3] # buradaki : ifadesi slice'dır. Dilimlemek anlamında, ama bu işlem için kullanılır

array([20, 21, 22])

In [203]:
a[3:] # 3.indexten kaptır sonuna kadar devam et 

array([23, 24, 25, 26, 27, 28, 29])

In [207]:
a[1::2] # 1.indexten kaptır 2şer 2 şer sonuna kadar devam et

array([21, 23, 25, 27, 29])

In [209]:
# iki boyutlu slice işlemleri

In [221]:
m = np.random.randint(10, size=(5,5))
m

array([[7, 1, 9, 0, 4],
       [6, 3, 4, 7, 9],
       [2, 6, 1, 4, 0],
       [9, 5, 0, 9, 6],
       [4, 3, 6, 9, 5]])

In [263]:
m[:,0] 

# böyle virgülle ayırınca virgülden öncesi satırları, sonra sütunları belirtir. 
# burada 0.sütunun tüm satırlarını getir dedik

array([7, 6, 2, 9, 4])

# Fancy Index ile Elemanlara Erişmek

İleride hem Pandas kütüphanelerinde hem de Numpy arraylerinde çok sıkça kullanacağız. Bu sebeple burası çok önemli!

In [280]:
import numpy as np
v = np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

Örneğin ben bu array'de 1, 3 ve 5 numaralı indexleri almak istersem şöyle yapabilirim:

In [283]:
v[1]

3

In [285]:
v[3]

9

In [287]:
v[5]

15

In [297]:
# ya da bir dizi içerisine koyup diziyi oynatabilirim

elemanListesi=np.array([v[1],v[3],v[5]])
elemanListesi

array([ 3,  9, 15])

In [299]:
# ancak elimizdeki index sayısı ve liste içerisindeki eleman sayısı arttıkça işler karışmaya başlaycak

In [309]:
indexListesi = np.array([1,3,5]) # bu şekilde listeye indexleri koyarsam
v[indexListesi] # bu şekilde de çağırırsam istediğimi tekte yapmış olurum. Buna "Fancy index" denir

array([ 3,  9, 15])

In [313]:
# İki boyutta fancy index

In [323]:
v2 = np.random.randint(16,size=(4,5))
v2

array([[ 9,  6,  4, 13, 11],
       [ 5, 11,  3, 14, 11],
       [ 0,  4, 11, 10, 15],
       [ 3, 13, 15, 15,  5]])

In [329]:
row_indexes = np.array([1,2])
column_indexes = np.array([3,4])

In [338]:
v2[row_indexes,column_indexes] # yapmış olduk

array([14, 15])

In [342]:
# Slice ile Fancy bir arada

v2[0:,[1,2]]

array([[ 6,  4],
       [11,  3],
       [ 4, 11],
       [13, 15]])

# Koşullu Eleman İşlemleri

In [347]:
import numpy as np
v = np.array([1,2,3,4,5])
v

array([1, 2, 3, 4, 5])

In [359]:
v > 3     # gitti her eleman için bu eleman 4'den büyük mü diye sordu

# sağlanan var mı yok mu kontrolünü yaptık ancak bunu sağlayan ya da sağlamayanları nasıl alacağız?

array([False, False, False,  True,  True])

In [363]:
v[v>3] # fency kullanımı ile sağlayanları aldık

array([4, 5])

In [371]:
v[v%2!=0] # tek olanlar

array([1, 3, 5])

# Numpy Arrayleri Üzerinde Matematiksel İşlemler

In [391]:
v

array([1, 2, 3, 4, 5])

In [376]:
v*5 # ile dizi içerisindeki tüm elemanları çarpabiliriz

array([ 5, 10, 15, 20, 25])

In [380]:
v/4

array([0.25, 0.5 , 0.75, 1.  , 1.25])

In [386]:
v**3

array([  1,   8,  27,  64, 125], dtype=int32)

In [389]:
v**2*10/7-15

array([-13.57142857,  -9.28571429,  -2.14285714,   7.85714286,
        20.71428571])

aslında arraylere bu işlemleri uyguladığımızda arkaplanda bazı fonksiyonlar çalışıyor.

In [403]:
np.subtract(v,15) # v-15 denince olan şey

array([-14, -13, -12, -11, -10])

In [407]:
np.add(v,10) # v+10 yapınca olan şey

array([11, 12, 13, 14, 15])

In [413]:
np.multiply(v,2) # v*2 yapınca çalışan fonksiyon

array([ 2,  4,  6,  8, 10])

In [415]:
np.divide(v,5) # v/5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [417]:
np.power(v,3) # v**3 demek

array([  1,   8,  27,  64, 125], dtype=int32)

In [419]:
np.mod(v,2) # v%2 demek

array([1, 0, 1, 0, 1], dtype=int32)

In [421]:
np.absolute(v) # mutlak değerli v arrayi

array([1, 2, 3, 4, 5])

In [431]:
np.sin(30) 

# çıktının 0.5 çıkmamasının sebebi numpy içeriye derece değil radyan alıyor. 
# 30xpi/180 yazarsan radyan cinsinden aradığını bulursun

-0.9880316240928618

In [437]:
np.cos(180)

-0.5984600690578581

In [443]:
v = np.array([3,9,27])

In [457]:
np.log(v) # log e tabanındaymış, 10 değil. 

np.log10([10,100,1000]) # Dereceyi istersek ayarlayabiliriz

array([1., 2., 3.])

# Numpy ile İki Bilinmeyenli Denklem Çözümü

5*x0 + x1 = 12

x0 + 3*x1 = 10

Bu denklemi bir tane kütüphane kullanarak çözdüreceğiz

Bunu yaparken bu ifadeyi numpyın anlayacağı bir şekle sokmak gerekiyor. Bunu yaparken de katsayıları bir diziye, diğerlerini bir diziye koyduktan sonra solve isimli fonksiyonu kullanarak bunu çözceceğiz

In [482]:
a = np.array([[5,1],[1,3]]) # Katsayılar Arrayi. 1.denklemde 5 ve 1 katsayıları, 2.denklemde 3 ve 1 katsayıları var
b = np.array([12,10]) # eşitliğin sağındaki değerler

In [484]:
a

array([[5, 1],
       [1, 3]])

In [486]:
b

array([12, 10])

In [488]:
x = np.linalg.solve(a,b) 

# lineercebir için olan linalg kütüpünün solve fonksiyonunu 2 bilinmeyenli denklem için kullandık

In [493]:
x # x0 = 1.85714286    x1 = 2.71428571   olarak buldu

array([1.85714286, 2.71428571])